CREATE PROCEDURE [dbo].[GenerateAllTableTypes](
	@SchemaName NVARCHAR(MAX)
)
AS
BEGIN
	DECLARE c_Tables CURSOR FOR 
		SELECT
			TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
			AND TABLE_SCHEMA = @SchemaName
	;

	DECLARE @TableName NVARCHAR(MAX);
	DECLARE @DDL NVARCHAR(MAX) = '--This script is generated by the GenerateAllTableTypes procedure in the database.' + CHAR(10) + 
		'--If you need to adjust these types because of a change in the base tables, run the aforementioned procedure.' + CHAR(10);

	OPEN c_Tables
	FETCH NEXT FROM c_Tables INTO @TableName
	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC GenerateTableType @SchemaName, @TableName, @DDL OUTPUT;
		FETCH NEXT FROM c_Tables INTO @TableName
		IF(@@FETCH_STATUS = 0)
			SET @DDL = @DDL + 'GO' + CHAR(10);
	END;

	PRINT @DDL;
END;
