CREATE PROCEDURE [dbo].[GenerateAllHistoryTriggerDDL]
	@SchemaName NVARCHAR(MAX),
	@ArchiveSchema NVARCHAR(MAX) = 'Archive'
AS
BEGIN
	DECLARE c_Tables CURSOR FOR 
		SELECT
			TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
			AND TABLE_SCHEMA = @SchemaName
	;

	DECLARE @TableName NVARCHAR(MAX);
	DECLARE @DDL VARCHAR(MAX) = '--This script is generated by the GenerateAllHistoryTriggerDDL procedure in the database.' + CHAR(10)
		+ '--If you need to adjust these triggers because of a change in the base tables, run the aforementioned procedure' + CHAR(10);

	OPEN c_Tables;
	FETCH NEXT FROM c_Tables INTO @TableName;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		EXEC GenerateHistoryTriggerDDL @SchemaName, @TableName, @DDL OUTPUT, @ArchiveSchema;

		FETCH NEXT FROM c_Tables INTO @TableName
		IF(@@FETCH_STATUS = 0)
			SET @DDL = @DDL + 'GO' + CHAR(10);
	END;

	PRINT @DDL;
END
