CREATE PROCEDURE [dbo].[GetTableColumnData]
(
	@TableName NVARCHAR(MAX),
	@SchemaName NVARCHAR(MAX),
	@OutputCursor CURSOR VARYING OUTPUT
)
AS
BEGIN
	SET @OutputCursor = CURSOR
	FORWARD_ONLY STATIC FOR
	SELECT
		COLUMN_NAME,
		DATA_TYPE,
		CHARACTER_MAXIMUM_LENGTH
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = @TableName
		AND TABLE_SCHEMA = @SchemaName
	ORDER BY ORDINAL_POSITION

	OPEN @OutputCursor
END;